/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Metodo;
import java.sql.Date;
import javax.swing.JOptionPane;
import modelo.Cliente;

/**
 *
 * @author ben95
 */
public class Form_actualizarCliente extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_actualizarCliente.class.getName());

    /**
     * Creates new form Actualizar
     */
    public Form_actualizarCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_limpiarAC = new javax.swing.JButton();
        jbtn_buscarIDCliente = new javax.swing.JButton();
        jtxt_idClienteAC = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_fecNacClienteAC = new javax.swing.JTextField();
        jtxt_telefonoClienteAC = new javax.swing.JTextField();
        jtxt_direccionClienteAC = new javax.swing.JTextField();
        jtxt_rutClienteAC = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jbtn_volverAC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtn_actualizarClienteAC = new javax.swing.JButton();
        jtxt_apPaternoAC = new javax.swing.JTextField();
        jtxt_nombreClienteAC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jbtn_limpiarAC.setText("Limpiar");
        jbtn_limpiarAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarACActionPerformed(evt);
            }
        });

        jbtn_buscarIDCliente.setText("Buscar");
        jbtn_buscarIDCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarIDClienteActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese la ID del Cliente :");

        jLabel7.setText("Fecha de Nacimiento :");

        jLabel6.setText("Teléfono :");

        jLabel5.setText("Dirección :");

        jLabel4.setText("Rut :");

        jbtn_volverAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/regresar.png"))); // NOI18N
        jbtn_volverAC.setText("Volver");
        jbtn_volverAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverACActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("ACTUALIZAR CLIENTE");

        jbtn_actualizarClienteAC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ok.png"))); // NOI18N
        jbtn_actualizarClienteAC.setText("Actualizar");
        jbtn_actualizarClienteAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarClienteACActionPerformed(evt);
            }
        });

        jtxt_apPaternoAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_apPaternoACActionPerformed(evt);
            }
        });

        jtxt_nombreClienteAC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_nombreClienteACActionPerformed(evt);
            }
        });

        jLabel1.setText("Apellido Paterno :");

        jLabel2.setText("Nombre :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxt_apPaternoAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_nombreClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_rutClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_idClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_direccionClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_telefonoClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_fecNacClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_buscarIDCliente)
                            .addComponent(jbtn_limpiarAC)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jbtn_volverAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtn_actualizarClienteAC)))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtxt_idClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxt_nombreClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jtxt_apPaternoAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jtxt_rutClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jtxt_direccionClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jtxt_fecNacClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jtxt_telefonoClienteAC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 101, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_buscarIDCliente)
                        .addGap(18, 18, 18)
                        .addComponent(jbtn_limpiarAC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbtn_actualizarClienteAC)
                            .addComponent(jbtn_volverAC, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_nombreClienteACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_nombreClienteACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_nombreClienteACActionPerformed

    private void jtxt_apPaternoACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_apPaternoACActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_apPaternoACActionPerformed

    private void jbtn_actualizarClienteACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarClienteACActionPerformed

        int idCliente = Integer.parseInt(this.jtxt_idClienteAC.getText());
        String rutCliente = this.jtxt_rutClienteAC.getText();
        String nombre = this.jtxt_nombreClienteAC.getText();
        String apPaterno = this.jtxt_apPaternoAC.getText();
        String direccion = this.jtxt_direccionClienteAC.getText();
        Date fecNac = Date.valueOf(this.jtxt_fecNacClienteAC.getText());
        int telefono = Integer.parseInt(this.jtxt_telefonoClienteAC.getText());

        Cliente c = new Cliente(rutCliente, nombre, apPaterno, direccion, fecNac, telefono, idCliente);

        Metodo m = new Metodo();

        if (m.actualizarCliente(c)) {

            JOptionPane.showMessageDialog(this, "Cliente Actualizado con Exito!!", "Actualizar Cliente", 1);

        } else {
            JOptionPane.showMessageDialog(this, "Cliente NO Actualizado", "Actualizar Cliente", 0);

        }

    }//GEN-LAST:event_jbtn_actualizarClienteACActionPerformed

    private void jbtn_volverACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverACActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_volverACActionPerformed

    private void jbtn_limpiarACActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarACActionPerformed

        this.jtxt_idClienteAC.setText("");
        this.jtxt_nombreClienteAC.setText("");
        this.jtxt_apPaternoAC.setText("");
        this.jtxt_rutClienteAC.setText("");
        this.jtxt_direccionClienteAC.setText("");
        this.jtxt_telefonoClienteAC.setText("");
        this.jtxt_fecNacClienteAC.setText("");


    }//GEN-LAST:event_jbtn_limpiarACActionPerformed

    private void jbtn_buscarIDClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarIDClienteActionPerformed

        int id = Integer.parseInt(this.jtxt_idClienteAC.getText());

        Metodo m = new Metodo();

        Cliente c = m.buscarCliente(id);
        
        this.jtxt_rutClienteAC.setText(c.getRutCliente());
        this.jtxt_nombreClienteAC.setText(c.getNombre());
        this.jtxt_apPaternoAC.setText(c.getApPaterno());
        this.jtxt_direccionClienteAC.setText(c.getDireccion());
        this.jtxt_fecNacClienteAC.setText(String.valueOf(c.getFecNac()));
        this.jtxt_telefonoClienteAC.setText(String.valueOf(c.getTelefono()));

    }//GEN-LAST:event_jbtn_buscarIDClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_actualizarCliente().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton jbtn_actualizarClienteAC;
    private javax.swing.JButton jbtn_buscarIDCliente;
    private javax.swing.JButton jbtn_limpiarAC;
    private javax.swing.JButton jbtn_volverAC;
    private javax.swing.JTextField jtxt_apPaternoAC;
    private javax.swing.JTextField jtxt_direccionClienteAC;
    private javax.swing.JTextField jtxt_fecNacClienteAC;
    private javax.swing.JTextField jtxt_idClienteAC;
    private javax.swing.JTextField jtxt_nombreClienteAC;
    private javax.swing.JTextField jtxt_rutClienteAC;
    private javax.swing.JTextField jtxt_telefonoClienteAC;
    // End of variables declaration//GEN-END:variables
}
