/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Metodo;
import javax.swing.JOptionPane;
import modelo.Insumo;

/**
 *
 * @author DxJtR
 */
public class Form_actualizarProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_actualizarProducto.class.getName());

    /**
     * Creates new form From_actualizarProducto
     */
    public Form_actualizarProducto() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_actProdID = new javax.swing.JTextField();
        jtxt_actProdNombre = new javax.swing.JTextField();
        jtxt_actProdPrecio = new javax.swing.JTextField();
        jtxt_actProdStock = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtn_actualizarProd = new javax.swing.JButton();
        jbtn_buscarIDProd = new javax.swing.JButton();
        jbtn_volverAP = new javax.swing.JButton();
        jbtn_limpiarAP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ACTUALIZAR PRODUCTO");

        jLabel2.setText("Ingrese la ID del Producto :");

        jtxt_actProdID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_actProdIDActionPerformed(evt);
            }
        });

        jtxt_actProdStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_actProdStockActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre :");

        jLabel4.setText("Precio :");

        jLabel5.setText("Stock :");

        jbtn_actualizarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ok.png"))); // NOI18N
        jbtn_actualizarProd.setText("Actualizar");
        jbtn_actualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarProdActionPerformed(evt);
            }
        });

        jbtn_buscarIDProd.setText("Buscar");
        jbtn_buscarIDProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarIDProdActionPerformed(evt);
            }
        });

        jbtn_volverAP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/regresar.png"))); // NOI18N
        jbtn_volverAP.setText("Volver");
        jbtn_volverAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverAPActionPerformed(evt);
            }
        });

        jbtn_limpiarAP.setText("Limpiar");
        jbtn_limpiarAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarAPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 182, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(210, 210, 210))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbtn_volverAP)
                                .addGap(106, 106, 106)))
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxt_actProdID, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_actProdPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_actProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxt_actProdStock, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(58, 506, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbtn_buscarIDProd)
                    .addComponent(jbtn_actualizarProd)
                    .addComponent(jbtn_limpiarAP))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_actProdID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarIDProd)
                    .addComponent(jLabel2))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxt_actProdNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_limpiarAP))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_actProdPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_actProdStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_actualizarProd)
                    .addComponent(jbtn_volverAP))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_actualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarProdActionPerformed
        
        int idInsumo = Integer.parseInt(this.jtxt_actProdID.getText());
        String nombre = this.jtxt_actProdNombre.getText();
        int precio = Integer.parseInt(this.jtxt_actProdPrecio.getText());
        int stock = Integer.parseInt(this.jtxt_actProdStock.getText());
        
        Insumo i = new Insumo(nombre, idInsumo, precio, stock,null,null);
        
        Metodo m = new Metodo();
        
        if(m.actualizarInsumo(i)){
            
            JOptionPane.showMessageDialog(this,"Producto Actualizado con Exito!!","Actualizar Producto",1 );
        
        }
        else{
            JOptionPane.showMessageDialog(this,"Producto NO Actualizado","Actualizar Producto",0 );
        
        } 
        
    }//GEN-LAST:event_jbtn_actualizarProdActionPerformed

    private void jtxt_actProdStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_actProdStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_actProdStockActionPerformed

    private void jbtn_buscarIDProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarIDProdActionPerformed
        
        int id = Integer.parseInt(this.jtxt_actProdID.getText());
        
        Metodo m = new Metodo();
        
        Insumo i = m.buscarInsumo(id);
        
        this.jtxt_actProdNombre.setText(i.getNombre());
        this.jtxt_actProdPrecio.setText(String.valueOf(i.getPrecio()));
        this.jtxt_actProdStock.setText(String.valueOf(i.getStock()));
    }//GEN-LAST:event_jbtn_buscarIDProdActionPerformed

    private void jbtn_volverAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverAPActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_volverAPActionPerformed

    private void jtxt_actProdIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_actProdIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_actProdIDActionPerformed

    private void jbtn_limpiarAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarAPActionPerformed
        
        this.jtxt_actProdID.setText("");
        this.jtxt_actProdNombre.setText("");
        this.jtxt_actProdPrecio.setText("");
        this.jtxt_actProdStock.setText("");
    }//GEN-LAST:event_jbtn_limpiarAPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_actualizarProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtn_actualizarProd;
    private javax.swing.JButton jbtn_buscarIDProd;
    private javax.swing.JButton jbtn_limpiarAP;
    private javax.swing.JButton jbtn_volverAP;
    private javax.swing.JTextField jtxt_actProdID;
    private javax.swing.JTextField jtxt_actProdNombre;
    private javax.swing.JTextField jtxt_actProdPrecio;
    private javax.swing.JTextField jtxt_actProdStock;
    // End of variables declaration//GEN-END:variables
}
