
package vista;

/**
 *
 * @author DxJtR
 */
public class Form_menuProducto extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_menuProducto.class.getName());

    /**
     * Creates new form Form_RegistroInsumo
     */
    public Form_menuProducto() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_agregarProd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_actualizarProd = new javax.swing.JButton();
        jbtn_eliminarProd = new javax.swing.JButton();
        jbtn_listarProductos = new javax.swing.JButton();
        jbtn_volverGP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_agregarProd.setText("Agregar Producto");
        jbtn_agregarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarProdActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("GESTIÓN DE PRODUCTOS");

        jbtn_actualizarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/act datos.png"))); // NOI18N
        jbtn_actualizarProd.setText("Actualizar Producto");
        jbtn_actualizarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarProdActionPerformed(evt);
            }
        });

        jbtn_eliminarProd.setText("Eliminar Producto");
        jbtn_eliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarProdActionPerformed(evt);
            }
        });

        jbtn_listarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/catalogo.png"))); // NOI18N
        jbtn_listarProductos.setText("Lista de Productos");
        jbtn_listarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarProductosActionPerformed(evt);
            }
        });

        jbtn_volverGP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/regresar.png"))); // NOI18N
        jbtn_volverGP.setText("Volver");
        jbtn_volverGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverGPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addGap(170, 170, 170))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jbtn_volverGP))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtn_eliminarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_listarProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_actualizarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtn_agregarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addComponent(jbtn_agregarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jbtn_actualizarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbtn_eliminarProd, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jbtn_listarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbtn_volverGP)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarProdActionPerformed
        
        Form_agregarProducto fap = new Form_agregarProducto();
        fap.setVisible(true);
        
        
        
    }//GEN-LAST:event_jbtn_agregarProdActionPerformed

    private void jbtn_listarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarProductosActionPerformed
        
        Form_listaProductos cProd = new Form_listaProductos();
        cProd.setVisible(true);
        
    }//GEN-LAST:event_jbtn_listarProductosActionPerformed

    private void jbtn_volverGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverGPActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_volverGPActionPerformed

    private void jbtn_actualizarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarProdActionPerformed
        
        Form_actualizarProducto faProduc = new Form_actualizarProducto();
        faProduc.setVisible(true);
        
        
        
         
    }//GEN-LAST:event_jbtn_actualizarProdActionPerformed

    private void jbtn_eliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarProdActionPerformed
        
        Form_eliminarProducto fep = new Form_eliminarProducto();
        fep.setVisible(true);
    }//GEN-LAST:event_jbtn_eliminarProdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_menuProducto().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn_actualizarProd;
    private javax.swing.JButton jbtn_agregarProd;
    private javax.swing.JButton jbtn_eliminarProd;
    private javax.swing.JButton jbtn_listarProductos;
    private javax.swing.JButton jbtn_volverGP;
    // End of variables declaration//GEN-END:variables
}
