/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.Metodo;
import javax.swing.JOptionPane;
import modelo.Empleado;

/**
 *
 * @author DxJtR
 */
public class Form_actualizarEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_actualizarEmpleado.class.getName());

    /**
     * Creates new form From_actualizarProducto
     */
    public Form_actualizarEmpleado() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_actEmpleadoID = new javax.swing.JTextField();
        jtxt_actEmpNombre = new javax.swing.JTextField();
        jtxt_actEmpApPaterno = new javax.swing.JTextField();
        jtxt_actEmpRUT = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtn_actualizarEmp = new javax.swing.JButton();
        jbtn_buscarIDEmp = new javax.swing.JButton();
        jbtn_volverAE = new javax.swing.JButton();
        jbtn_limpiarAE = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxt_actEmpCargo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ACTUALIZAR EMPLEADO");

        jLabel2.setText("Ingrese la ID del Empleado :");

        jtxt_actEmpleadoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_actEmpleadoIDActionPerformed(evt);
            }
        });

        jtxt_actEmpRUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxt_actEmpRUTActionPerformed(evt);
            }
        });

        jLabel3.setText("Nombre :");

        jLabel4.setText("Apellido Paterno :");

        jLabel5.setText("RUT :");

        jbtn_actualizarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ok.png"))); // NOI18N
        jbtn_actualizarEmp.setText("Actualizar");
        jbtn_actualizarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarEmpActionPerformed(evt);
            }
        });

        jbtn_buscarIDEmp.setText("Buscar");
        jbtn_buscarIDEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_buscarIDEmpActionPerformed(evt);
            }
        });

        jbtn_volverAE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/regresar.png"))); // NOI18N
        jbtn_volverAE.setText("Volver");
        jbtn_volverAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverAEActionPerformed(evt);
            }
        });

        jbtn_limpiarAE.setText("Limpiar");
        jbtn_limpiarAE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_limpiarAEActionPerformed(evt);
            }
        });

        jLabel6.setText("Cargo: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(200, 200, 200))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jbtn_volverAE)
                        .addGap(107, 107, 107)))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jtxt_actEmpNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbtn_buscarIDEmp)
                            .addComponent(jbtn_actualizarEmp)
                            .addComponent(jbtn_limpiarAE))
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxt_actEmpleadoID, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jtxt_actEmpApPaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jtxt_actEmpRUT, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jtxt_actEmpCargo))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_actEmpleadoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtn_buscarIDEmp)
                    .addComponent(jLabel2))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxt_actEmpNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jbtn_limpiarAE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxt_actEmpApPaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtxt_actEmpRUT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtxt_actEmpCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_actualizarEmp)
                    .addComponent(jbtn_volverAE))
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_actualizarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarEmpActionPerformed
        
        int idEmpleado = Integer.parseInt(this.jtxt_actEmpleadoID.getText());
        String rut = this.jtxt_actEmpRUT.getText();
        String nombre = this.jtxt_actEmpNombre.getText();
        String apPaterno = this.jtxt_actEmpApPaterno.getText();
        String cargo = this.jtxt_actEmpCargo.getText();
        
        Empleado e = new Empleado(idEmpleado, rut, nombre, apPaterno, cargo);
        
        Metodo m = new Metodo();
        
        if(m.actualizarEmpleado(e)){
            
            JOptionPane.showMessageDialog(this,"Empleado Actualizado con Exito!!","Actualizar Empleado",1 );
        
        }
        else{
            JOptionPane.showMessageDialog(this,"Empleado NO Actualizado","Actualizar Empleado",0 );
        
        } 
        
    }//GEN-LAST:event_jbtn_actualizarEmpActionPerformed

    private void jtxt_actEmpRUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_actEmpRUTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_actEmpRUTActionPerformed

    private void jbtn_buscarIDEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarIDEmpActionPerformed
        
        int id = Integer.parseInt(this.jtxt_actEmpleadoID.getText());
        
        Metodo m = new Metodo();
        
        Empleado e = m.buscarEmpleado(id);

        this.jtxt_actEmpNombre.setText(e.getNombre());
        this.jtxt_actEmpApPaterno.setText(e.getApPaterno());
        this.jtxt_actEmpRUT.setText(e.getRutEmpleado());
        this.jtxt_actEmpCargo.setText(e.getCargo());
        
    }//GEN-LAST:event_jbtn_buscarIDEmpActionPerformed

    private void jbtn_volverAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverAEActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_volverAEActionPerformed

    private void jtxt_actEmpleadoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxt_actEmpleadoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxt_actEmpleadoIDActionPerformed

    private void jbtn_limpiarAEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_limpiarAEActionPerformed
        
        this.jtxt_actEmpleadoID.setText("");
        this.jtxt_actEmpNombre.setText("");
        this.jtxt_actEmpApPaterno.setText("");
        this.jtxt_actEmpRUT.setText("");
        this.jtxt_actEmpCargo.setText("");
    }//GEN-LAST:event_jbtn_limpiarAEActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_actualizarEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtn_actualizarEmp;
    private javax.swing.JButton jbtn_buscarIDEmp;
    private javax.swing.JButton jbtn_limpiarAE;
    private javax.swing.JButton jbtn_volverAE;
    private javax.swing.JTextField jtxt_actEmpApPaterno;
    private javax.swing.JTextField jtxt_actEmpCargo;
    private javax.swing.JTextField jtxt_actEmpNombre;
    private javax.swing.JTextField jtxt_actEmpRUT;
    private javax.swing.JTextField jtxt_actEmpleadoID;
    // End of variables declaration//GEN-END:variables
}
