
package vista;

/**
 *
 * @author DxJtR
 */
public class Form_menuEmpleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Form_menuEmpleado.class.getName());

    /**
     * Creates new form Form_RegistroInsumo
     */
    public Form_menuEmpleado() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtn_agregarEmp = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtn_actualizarEmp = new javax.swing.JButton();
        jbtn_eliminarEmp = new javax.swing.JButton();
        jbtn_listarEmp = new javax.swing.JButton();
        jbtn_volverGP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbtn_agregarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/Registrar Usuario.png"))); // NOI18N
        jbtn_agregarEmp.setText("Agregar Empleado");
        jbtn_agregarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_agregarEmpActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Registro Empleado");

        jbtn_actualizarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/act datos.png"))); // NOI18N
        jbtn_actualizarEmp.setText("Actualizar Empleado");
        jbtn_actualizarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_actualizarEmpActionPerformed(evt);
            }
        });

        jbtn_eliminarEmp.setText("Eliminar Empleado");
        jbtn_eliminarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_eliminarEmpActionPerformed(evt);
            }
        });

        jbtn_listarEmp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/catalogo.png"))); // NOI18N
        jbtn_listarEmp.setText("Lista de Empleados");
        jbtn_listarEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_listarEmpActionPerformed(evt);
            }
        });

        jbtn_volverGP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/regresar.png"))); // NOI18N
        jbtn_volverGP.setText("Volver");
        jbtn_volverGP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_volverGPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(216, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(208, 208, 208))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jbtn_volverGP)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbtn_listarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_eliminarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtn_actualizarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                    .addComponent(jbtn_agregarEmp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jbtn_agregarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbtn_actualizarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtn_eliminarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jbtn_listarEmp, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jbtn_volverGP)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_agregarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_agregarEmpActionPerformed
              
        Form_agregarEmpleado fap = new Form_agregarEmpleado();
        fap.setVisible(true);
        
    }//GEN-LAST:event_jbtn_agregarEmpActionPerformed

    private void jbtn_listarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_listarEmpActionPerformed
        
        Form_listaEmpleados fle = new Form_listaEmpleados();
        fle.setVisible(true);
        
    }//GEN-LAST:event_jbtn_listarEmpActionPerformed

    private void jbtn_volverGPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_volverGPActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtn_volverGPActionPerformed

    private void jbtn_actualizarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_actualizarEmpActionPerformed
            
        Form_actualizarEmpleado fae = new Form_actualizarEmpleado();
        fae.setVisible(true);
         
        
    }//GEN-LAST:event_jbtn_actualizarEmpActionPerformed

    private void jbtn_eliminarEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_eliminarEmpActionPerformed
        
        Form_eliminarEmpleado fee = new Form_eliminarEmpleado();
        fee.setVisible(true);
        
    }//GEN-LAST:event_jbtn_eliminarEmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Form_menuEmpleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtn_actualizarEmp;
    private javax.swing.JButton jbtn_agregarEmp;
    private javax.swing.JButton jbtn_eliminarEmp;
    private javax.swing.JButton jbtn_listarEmp;
    private javax.swing.JButton jbtn_volverGP;
    // End of variables declaration//GEN-END:variables
}
